# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nirmalya_public' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nirmalya_public

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'XLPagerTabStrip', '~> 8.0'

end
